# Generated by Django 4.1.2 on 2022-10-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('Nombre', models.CharField(max_length=20)),
                ('cedula', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('numero_celular', models.IntegerField(max_length=10)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
